package com.clockmods.background

/**
 * Kotlin property aliases for the Java-compatible [ClockPreferences] facade.
 *
 * The facade deliberately keeps its method-shaped API because it is consumed by
 * the public SDK and by existing Java integrations.  Kotlin callers can use the
 * natural property spelling without changing any of those JVM method names.
 */
val ClockPreferences.backgroundMode: String get() = getBackgroundMode()
val ClockPreferences.isDimBackground: Boolean get() = isDimBackground()
val ClockPreferences.isScheduleDimBackground: Boolean get() = isScheduleDimBackground()
val ClockPreferences.dimStartMinutes: Int get() = getDimStartMinutes()
val ClockPreferences.dimEndMinutes: Int get() = getDimEndMinutes()
val ClockPreferences.timeFontScale: Float get() = getTimeFontScale()
val ClockPreferences.dateFontScale: Float get() = getDateFontScale()
val ClockPreferences.timeColor: Int get() = getTimeColor()
val ClockPreferences.dateColor: Int get() = getDateColor()
val ClockPreferences.isShowStatusIcons: Boolean get() = isShowStatusIcons()
val ClockPreferences.statusIconScale: Float get() = getStatusIconScale()
val ClockPreferences.isBlinkColon: Boolean get() = isBlinkColon()
val ClockPreferences.isAnimateTimeChanges: Boolean get() = isAnimateTimeChanges()
val ClockPreferences.timeTransition: String get() = getTimeTransition()
val ClockPreferences.isHourlyChimeEnabled: Boolean get() = isHourlyChimeEnabled()
val ClockPreferences.isHalfHourChimeEnabled: Boolean get() = isHalfHourChimeEnabled()
val ClockPreferences.isHourlyChimeQuietEnabled: Boolean get() = isHourlyChimeQuietEnabled()
val ClockPreferences.hourlyChimeQuietStart: Int get() = getHourlyChimeQuietStart()
val ClockPreferences.hourlyChimeQuietEnd: Int get() = getHourlyChimeQuietEnd()
val ClockPreferences.isBoldText: Boolean get() = isBoldText()
val ClockPreferences.fontFamily: String get() = getFontFamily()
val ClockPreferences.isShowSeconds: Boolean get() = isShowSeconds()
val ClockPreferences.isShowLunar: Boolean get() = isShowLunar()
val ClockPreferences.isAutoStart: Boolean get() = isAutoStart()
val ClockPreferences.calendarWeekStart: Int get() = getCalendarWeekStart()
val ClockPreferences.isCalendarHighlightWeekends: Boolean get() = isCalendarHighlightWeekends()
val ClockPreferences.calendarTheme: String get() = getCalendarTheme()
val ClockPreferences.isSmallSeconds: Boolean get() = isSmallSeconds()
val ClockPreferences.isPortraitStacked: Boolean get() = isPortraitStacked()
val ClockPreferences.isDateLunarDualLine: Boolean get() = isDateLunarDualLine()
val ClockPreferences.isUse24Hour: Boolean get() = isUse24Hour()
val ClockPreferences.isClockUseEnglish: Boolean get() = isClockUseEnglish()
val ClockPreferences.clockLanguage: String get() = getClockLanguage()
val ClockPreferences.customMessage: String get() = getCustomMessage()
val ClockPreferences.weatherTemperatureUnit: String get() = getWeatherTemperatureUnit()
val ClockPreferences.datePatternCn: String get() = getDatePatternCn()
val ClockPreferences.datePatternEn: String get() = getDatePatternEn()
val ClockPreferences.screenOrientation: Int get() = getScreenOrientation()
val ClockPreferences.isUseNetworkTime: Boolean get() = isUseNetworkTime()
val ClockPreferences.syncIntervalMinutes: Int get() = getSyncIntervalMinutes()
val ClockPreferences.timeZoneId: String get() = getTimeZoneId()
val ClockPreferences.isWeatherEnabled: Boolean get() = isWeatherEnabled()
val ClockPreferences.isWeatherDetailed: Boolean get() = isWeatherDetailed()
val ClockPreferences.weatherIntervalMinutes: Int get() = getWeatherIntervalMinutes()
val ClockPreferences.weatherLocationMode: String get() = getWeatherLocationMode()
val ClockPreferences.weatherLocationId: String get() = getWeatherLocationId()
val ClockPreferences.weatherProvince: String get() = getWeatherProvince()
val ClockPreferences.weatherCity: String get() = getWeatherCity()
val ClockPreferences.weatherDistrict: String get() = getWeatherDistrict()
val ClockPreferences.weatherLatitude: Double get() = getWeatherLatitude()
val ClockPreferences.weatherLongitude: Double get() = getWeatherLongitude()
val ClockPreferences.isWeatherIconFill: Boolean get() = isWeatherIconFill()
val ClockPreferences.isWeatherIconDynamicColor: Boolean get() = isWeatherIconDynamicColor()
