// @vitest-environment jsdom
import {setLanguage} from '../src/core/i18n';
import {beforeEach,it,expect,vi} from 'vitest';
import {prefs} from '../src/core/prefs';
import {UltimateFace} from '../src/ui/ultimate-face';
import {secondaryFontSize} from '../src/ui/secondary-font-size';
import {fitSupportingRows} from '../src/format/responsive-layout';
beforeEach(()=>{vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue(null);localStorage.clear();document.body.replaceChildren();});
function mount(){prefs.setClockTheme('noir.instrument');const host=document.createElement('div');document.body.append(host);const rows={date:document.createElement('div'),lunar:document.createElement('div'),weather:document.createElement('div'),detail:document.createElement('div')};rows.date.textContent='10月9日 星期五';rows.lunar.textContent='八月廿九';rows.weather.textContent='晴 24℃';rows.detail.textContent='湿度 60%';const face=new UltimateFace(host,rows);const render=(w=1920,h=1080)=>face.render('noir.instrument',w,h,{hour:12,minute:8,second:36,month0:9,day:9,showSeconds:true,use24Hour:true,options:{animate:false,transition:'fade',colonVisible:true}});return{host,rows,render};}
it('changing one supporting role never resizes another region',()=>{const {rows,render}=mount();prefs.setDateFontSize(16);prefs.setSupportingFontSize(16);render();const date=rows.date.style.fontSize;prefs.setSupportingFontSize(80);render();expect(rows.date.style.fontSize).toBe(date);const weather=rows.weather.style.fontSize;prefs.setDateFontSize(80);render();expect(rows.weather.style.fontSize).toBe(weather);});
it('automatic typography grows with its viewport and manual pixels stay fixed',()=>{const {rows,render}=mount();render();const small=parseFloat(rows.date.style.fontSize);render(3840,2160);expect(parseFloat(rows.date.style.fontSize)).toBeGreaterThan(small*1.8);prefs.setDateFontSize(16);render();expect(rows.date.style.fontSize).toBe('16px');render(3840,2160);expect(rows.date.style.fontSize).toBe('16px');});
it('time scaling grows visibly before reaching the region boundary',()=>{const {host,render}=mount();prefs.setTimeFontScale(.5);render();const size=parseFloat((host.querySelector('[data-part=time]') as HTMLElement).style.fontSize);prefs.setTimeFontScale(1.5);render();expect(parseFloat((host.querySelector('[data-part=time]') as HTMLElement).style.fontSize)).toBeGreaterThan(size*1.5);});
it('automatic controls allow direct dragging and explicit return to automatic',()=>{const control=secondaryFontSize('日期','date','noir.instrument');expect(control.value()).toBe(0);control.input.value='36';control.input.dispatchEvent(new Event('input'));expect(control.value()).toBe(36);control.row.querySelector('button')!.click();expect(control.value()).toBe(0);});
it('classic supporting rows have independent space budgets',()=>{const first=fitSupportingRows(600,400,24,24,2,2,false),second=fitSupportingRows(600,400,80,24,2,2,false);expect(second.supportingSize).toBe(first.supportingSize);});

it('keeps automatic labels traditional after toggling',()=>{setLanguage('zh-Hant');try{const c=secondaryFontSize('日期','date','noir.instrument');c.row.querySelector('button')!.click();c.row.querySelector('button')!.click();expect(c.row.querySelector('.settings-slider-value')!.textContent).toBe('自動');}finally{setLanguage('zh-Hans');}});
