/** @vitest-environment jsdom */
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {installIdleCursor} from '../src/ui/idle-cursor';
import {cityName} from '../src/core/cities';
import {localizedAlmanac} from '../src/lunar/language';
import {localizeUiTree,traditional} from '../src/core/ui-language';
import {setLanguage,t} from '../src/core/i18n';
import {openTimePicker} from '../src/ui/time-picker';
import {materialIcon} from '../src/ui/material-icons';
import {LabelCarousel} from '../src/ui/label-carousel';
let dispose:(()=>void)|undefined;
beforeEach(()=>{document.body.innerHTML='';localStorage.clear();setLanguage('zh-Hans');Object.defineProperty(document,'hidden',{configurable:true,value:false});});
afterEach(()=>{dispose?.();dispose=undefined;vi.useRealTimers();vi.restoreAllMocks();});
const mouse=()=>document.dispatchEvent(Object.assign(new Event('pointermove'),{pointerType:'mouse'}));
describe('web language and interaction polish',()=>{
 it('localizes cities including IANA aliases and traditional names',()=>{expect(cityName('America/New_York','zh-Hans')).toBe('纽约');expect(cityName('US/Eastern','zh-Hant')).toBe('紐約');expect(cityName('America/New_York','en')).toBe('New York');expect(cityName('Asia/Shanghai','zh-Hant')).toBe('上海');});
 it('translates lunar details and almanac activities without mutating the Chinese cache',()=>{const en=localizedAlmanac(2026,7,7,'en');expect(en.natural).toContain('Lunar');expect(JSON.stringify(en)).not.toMatch(/[\p{Script=Han}]/u);const cn=localizedAlmanac(2026,7,7,'zh-Hans'),tw=localizedAlmanac(2026,7,7,'zh-Hant');expect(cn.natural).toContain('马');expect(tw.natural).toContain('馬');});
 it('converts interface copy but preserves user data and font names',()=>{document.body.innerHTML='<p>时钟设置与分钟</p><input value="自定义字体"/><select data-font-select><option>测试字体</option></select>';localizeUiTree(document.body,'zh-Hant');expect(document.querySelector('p')!.textContent).toBe('時鐘設置與分鐘');expect(document.querySelector('input')!.value).toBe('自定义字体');expect(document.querySelector('option')!.textContent).toBe('测试字体');expect(traditional('小时')).toBe('小時');});
 it('sets the document language even when restoring an already selected language',()=>{setLanguage('en');document.documentElement.lang='zh-Hans';setLanguage('en');expect(document.documentElement.lang).toBe('en');expect(t('timer_hours')).toBe('Hours');});
 it('shows app-localized time fields and applies their numeric values',()=>{setLanguage('en');HTMLDialogElement.prototype.showModal=function(){this.open=true;};HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new Event('close'));};const apply=vi.fn();openTimePicker(450,'Time',apply);const inputs=document.querySelectorAll<HTMLInputElement>('input');expect(inputs[0].getAttribute('aria-label')).toBe('Hours');expect(inputs[1].getAttribute('aria-label')).toBe('Minutes');inputs[0].value='9';inputs[1].value='15';document.querySelector('form')!.dispatchEvent(new Event('submit',{cancelable:true}));expect(apply).toHaveBeenCalledWith(555);expect(document.querySelector('dialog')).toBeNull();});
 it('hides after three seconds and restarts on movement, even while clock DOM changes',async()=>{vi.useFakeTimers();dispose=installIdleCursor();mouse();vi.advanceTimersByTime(2999);expect(document.documentElement.classList.contains('is-cursor-idle')).toBe(false);document.body.append(document.createElement('span'));await Promise.resolve();vi.advanceTimersByTime(1);expect(document.documentElement.classList.contains('is-cursor-idle')).toBe(true);mouse();expect(document.documentElement.classList.contains('is-cursor-idle')).toBe(false);vi.advanceTimersByTime(3000);expect(document.documentElement.classList.contains('is-cursor-idle')).toBe(true);});
 it('keeps the cursor visible while settings are open and ignores touch input',async()=>{vi.useFakeTimers();dispose=installIdleCursor();document.dispatchEvent(Object.assign(new Event('pointermove'),{pointerType:'touch'}));vi.advanceTimersByTime(4000);expect(document.documentElement.classList.contains('is-cursor-idle')).toBe(false);mouse();const dialog=document.createElement('dialog');dialog.open=true;document.body.append(dialog);await Promise.resolve();vi.advanceTimersByTime(4000);expect(document.documentElement.classList.contains('is-cursor-idle')).toBe(false);dialog.remove();await Promise.resolve();vi.advanceTimersByTime(3000);expect(document.documentElement.classList.contains('is-cursor-idle')).toBe(true);});
 it('uses real Material SVG paths with decorative accessibility semantics',()=>{const icon=materialIcon('schedule');expect(icon.tagName).toBe('svg');expect(icon.querySelector('path')).not.toBeNull();expect(icon.getAttribute('aria-hidden')).toBe('true');});
 it('shows the first calendar label in a static preview without starting a carousel timer',()=>{vi.useFakeTimers();const host=document.createElement('div'),carousel=new LabelCarousel(host);document.body.append(host);carousel.setItems([{text:'初九'}]);vi.advanceTimersByTime(20);expect(host.classList.contains('is-measuring')).toBe(false);expect(carousel.isActive).toBe(false);expect(vi.getTimerCount()).toBe(0);carousel.destroy();});
});
