import { almanacOf } from './lunar';
import type { Almanac } from './lunar';
import { traditional } from '../core/ui-language';
const english:Record<string,string>={
  "上梁": "Raise roof beams",
  "乘船": "Boating",
  "习艺": "Learn a craft",
  "交易": "Trade",
  "伐木": "Felling trees",
  "会亲友": "Meet friends and relatives",
  "作梁": "Make beams",
  "作灶": "Build a stove",
  "修坟": "Repair graves",
  "修造": "Renovation",
  "修门": "Repair doors",
  "修饰垣墙": "Repair walls",
  "入学": "Start school",
  "入宅": "Move into a home",
  "入殓": "Place in a coffin",
  "冠笄": "Coming-of-age ceremony",
  "出火": "Move a sacred flame",
  "出行": "Travel",
  "出货财": "Ship goods",
  "分居": "Establish separate households",
  "割蜜": "Harvest honey",
  "动土": "Break ground",
  "取渔": "Fishing",
  "合寿木": "Make a coffin",
  "合帐": "Prepare wedding bedding",
  "合脊": "Join roof ridges",
  "启钻": "Exhume a grave",
  "坏垣": "Demolish walls",
  "塑绘": "Sculpting and painting",
  "塞穴": "Seal openings",
  "嫁娶": "Marriage",
  "安床": "Install a bed",
  "安机械": "Install machinery",
  "安碓磑": "Install a mill",
  "安葬": "Burial",
  "安门": "Install doors",
  "安香": "Install an altar",
  "定磉": "Lay foundation stones",
  "平治道涂": "Repair roads",
  "开仓": "Open a granary",
  "开光": "Consecration",
  "开厕": "Build a latrine",
  "开市": "Open a business",
  "开柱眼": "Bore pillar joints",
  "开池": "Dig a pond",
  "开渠": "Dig a channel",
  "开生坟": "Prepare a grave",
  "归宁": "Visit maternal family",
  "归岫": "Return livestock",
  "成服": "Begin mourning",
  "扫舍": "House cleaning",
  "拆卸": "Demolition",
  "挂匾": "Hang a sign",
  "捕捉": "Trapping",
  "掘井": "Dig a well",
  "探病": "Visit the sick",
  "放水": "Release water",
  "教牛马": "Train livestock",
  "整手足甲": "Trim nails",
  "斋醮": "Ritual fasting",
  "断蚁": "Pest control",
  "普渡": "Offerings to wandering spirits",
  "架马": "Build scaffolding",
  "栽种": "Planting",
  "求医": "Seek medical care",
  "求嗣": "Pray for children",
  "沐浴": "Bathing",
  "治病": "Medical treatment",
  "牧养": "Herding",
  "理发": "Haircut",
  "畋猎": "Hunting",
  "盖屋": "Build a house",
  "破土": "Break ground for burial",
  "破屋": "Demolish a house",
  "祈福": "Pray for blessings",
  "祭祀": "Ancestral offerings",
  "移徙": "Relocation",
  "移柩": "Move a coffin",
  "立券": "Sign agreements",
  "立碑": "Erect a monument",
  "竖柱": "Raise pillars",
  "筑堤": "Build an embankment",
  "纳婿": "Welcome a son-in-law",
  "纳畜": "Acquire livestock",
  "纳财": "Receive money",
  "纳采": "Betrothal gifts",
  "经络": "Weaving",
  "结网": "Make nets",
  "置产": "Acquire property",
  "行丧": "Funeral rites",
  "补垣": "Mend walls",
  "裁衣": "Make clothes",
  "解除": "Cleansing rituals",
  "订盟": "Engagement",
  "词讼": "Legal proceedings",
  "诸事不宜": "No major activities advised",
  "谢土": "Thank the earth deity",
  "赴任": "Take office",
  "起基": "Lay foundations",
  "进人口": "Welcome household members",
  "造仓": "Build a granary",
  "造庙": "Build a temple",
  "造桥": "Build a bridge",
  "造畜稠": "Build livestock pens",
  "造船": "Build a boat",
  "造车器": "Make vehicles",
  "针灸": "Acupuncture",
  "问名": "Betrothal inquiry",
  "除服": "End mourning",
  "雇佣": "Hiring",
  "雕刻": "Carving",
  "馀事勿取": "Avoid other activities",
  "余事勿取": "Avoid other activities",
  "立春": "Start of Spring",
  "雨水": "Rain Water",
  "惊蛰": "Awakening of Insects",
  "春分": "Spring Equinox",
  "清明": "Qingming",
  "谷雨": "Grain Rain",
  "立夏": "Start of Summer",
  "小满": "Grain Buds",
  "芒种": "Grain in Ear",
  "夏至": "Summer Solstice",
  "小暑": "Minor Heat",
  "大暑": "Major Heat",
  "立秋": "Start of Autumn",
  "处暑": "End of Heat",
  "白露": "White Dew",
  "秋分": "Autumn Equinox",
  "寒露": "Cold Dew",
  "霜降": "Frost Descent",
  "立冬": "Start of Winter",
  "小雪": "Minor Snow",
  "大雪": "Major Snow",
  "冬至": "Winter Solstice",
  "小寒": "Minor Cold",
  "大寒": "Major Cold",
  "春节": "Spring Festival",
  "元宵节": "Lantern Festival",
  "龙头节": "Dragon Head Festival",
  "上巳节": "Shangsi Festival",
  "清明节": "Qingming Festival",
  "端午节": "Dragon Boat Festival",
  "七夕节": "Qixi Festival",
  "中元节": "Ghost Festival",
  "中秋节": "Mid-Autumn Festival",
  "重阳节": "Double Ninth Festival",
  "冬至节": "Winter Solstice",
  "腊八节": "Laba Festival",
  "小年": "Little New Year",
  "除夕": "Lunar New Year's Eve",
  "元旦": "New Year's Day",
  "妇女节": "Women's Day",
  "植树节": "Arbor Day",
  "劳动节": "Labour Day",
  "青年节": "Youth Day",
  "儿童节": "Children's Day",
  "建党节": "CPC Founding Day",
  "建军节": "Army Day",
  "教师节": "Teachers' Day",
  "国庆节": "National Day",
  "初伏": "Early Dog Days",
  "中伏": "Middle Dog Days",
  "末伏": "Late Dog Days"
};
const cache=new Map<string,Almanac>();
export function localizedAlmanac(year:number,month0:number,day:number,lang:string):Almanac {
 const original=almanacOf(year,month0,day);if(lang==='zh-Hans')return original;
 const key=[year,month0,day,lang].join('-');const old=cache.get(key);if(old)return old;
 const text=(s:string)=>lang==='zh-Hant'?traditional(s):english[s]??(/^[一二三四五六七八九]九$/.test(s)?'Winter nine-day period '+('一二三四五六七八九'.indexOf(s[0])+1):'Traditional observance');
 let natural=traditional(original.natural),shortLabel=traditional(original.shortLabel),bracketed=traditional(original.bracketed);
 if(lang==='en') {
  const date=new Date(Date.UTC(year,month0,day,12));
  natural='Lunar '+new Intl.DateTimeFormat('en-u-ca-chinese',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(date);
  shortLabel=new Intl.DateTimeFormat('en-u-ca-chinese',{month:'numeric',day:'numeric',timeZone:'UTC'}).format(date);bracketed=natural;
 }
 const result={natural,shortLabel,bracketed,festivals:original.festivals.map(text),suitable:original.suitable.map(text),avoid:original.avoid.map(text)};
 if(cache.size>600)cache.clear();cache.set(key,result);return result;
}
